[project]
name = "darkroom-blend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fake-bpy-module>=20251003",
]

[dependency-groups]
dev = [
    "python-lsp-ruff>=2.3.0",
    "python-lsp-server>=1.13.1",
]
